version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - wget https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip
      - unzip terraform_0.12.6_linux_amd64.zip
      - mv terraform /bin
      - terraform --version
  build:
    commands:
      - terraform init
      - terraform apply --auto-approve
